In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply
print ("libraries import successfully")

libraries import successfully

In [50]:
df=pd.read_csv("customer.csv")

In [51]:
import os
os.listdir()

['.ipynb_checkpoints',
 '.vs',
 'Advanced_Excel_Functions.xlsx',
 'Appiest Birthday Manthu_.docx',
 'CDA Drive link.xlsx',
 'certification of SDG.pdf',
 'CMM.pdf',
 'CodeChefBadge.png',
 'Costumer_data_analysis.ipynb',
 'customer.csv',
 'customer.csv.xls',
 'customer_cleaned.csv',
 'customer_data_analysis (1).pbix',
 'customer_data_analysis.pbix',
 'customer_data_analysis.pbix.zip',
 'desktop.ini',
 'Frnds Video.mp4',
 'Full Stack Developer Masterclass new pdf.pdf',
 'git cmds.pdf',
 'Git-2.54.0-64-bit.exe',
 'Git-2.54.0-arm64.exe',
 'HTML_certificate.jpg',
 'Hypothesis Testing.xlsx',
 'Jai Shree Ram.jpg',
 'Jai Shree Ram.pdf',
 'java imp points.docx',
 'java Unit-3(interfaces).pptx',
 'java Unit-3(Packages).pptx',
 'java Unit-4 Exception Handling.pptx',
 'java unit-4 Threads.pptx',
 'Java_Architecture_Essay.docx',
 'JS Var, Nullish,spread operators.pdf',
 'LATEST FROM MAY 2025.pdf',
 'long.jpg',
 'Machine_Learning_Introduction (1).pptx',
 'Machine_Learning_Introduction.pptx',
 'MAJOR PROJECT- NOTE TAKING WEB APP.zip',
 'Microsoft.Services.Store.winmd',
 'mongodb-windows-x86_64-8.3.2-signed (1).msi',
 'mongodb-windows-x86_64-8.3.2-signed.msi',
 'mysql-connector-net-26.7.0.msi',
 'mysql-installer-web-community-8.0.46.0 (1).msi',
 'mysql-installer-web-community-8.0.46.0.msi',
 'New_documents_for_Ravuri_Yasaswi_Venkata_Naga.zip',
 'orders_data (2).xlsx',
 'original_print.pdf',
 'pantechcertificate.pdf',
 'Passport .pdf',
 'progit.pdf',
 'PROJECT CONFERENCE CERTIFICATE.jpg',
 'RAVURI   YASASWI   VENKATA   NAGA   SRAVANI_ORIGINAL.pdf',
 'Ravuri  Yasaswi  Venkata  Naga  Sravani.pdf',
 'Ravuri Sravani_Android_Certificate.pdf',
 'RAVURI Y V N SRAVANI.pdf',
 'RAVURI YASASWI VENKATA NAGA SRAVANI.pdf',
 'RAVURI_YASASWI_VENKATA_NAGA_SRAVANI.pdf',
 'REVISED DOJ.jpeg',
 'R_D-Poster.png',
 'Screenshot_2021-08-12-17-32-29-45.jpg',
 'song (online-audio-converter.com).mp3',
 'song.unknown',
 'spotify_analysis_dataset.csv',
 'SQL.pdf',
 'Sravani_ PROJECT REPORT.pdf',
 'SSC.pdf',
 'Star Performer of the Month Certificate_Ravuri Sravani.pdf',
 'TableauDesktop-64bit-2026-1-1.exe',
 'TableauDesktop-64bit-2026-1-2.exe',
 'Talent Battle GD Course_Ravuri Yasaswi Venkata Naga Sravani.pdf',
 'Teddy_Bear_Candle_Business_Plan (1).pdf',
 'Unit-2.pptx',
 'Untitled spreadsheet.xlsx',
 'Untitled.ipynb']

In [52]:
df.head(10)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I100008,C199951,Male,65,Clothing,5,1500.40,Cash,10-07-2022,Emaar Square Mall
1,I100014,C138893,Male,55,Cosmetics,5,203.30,Cash,18-06-2021,Viaport Outlet
2,I100015,C132779,Female,35,Clothing,2,600.16,Debit Card,04-03-2021,Mall of Istanbul
3,I100024,C244411,Female,67,Books,3,45.45,Credit Card,05-01-2023,Emaar Square Mall
4,I100027,C150002,Female,19,Technology,4,4200.00,Cash,18-05-2022,Mall of Istanbul
5,I100028,C325553,Female,18,Clothing,1,300.08,Credit Card,19-06-2021,Metrocity
6,I100031,C378408,Male,18,Food & Beverage,3,15.69,Credit Card,23-06-2022,Emaar Square Mall
7,I100033,C278721,Male,56,Food & Beverage,4,20.92,Credit Card,19-10-2021,Zorlu Center
8,I100037,C122873,Female,63,Clothing,1,300.08,Debit Card,06-06-2021,Kanyon
9,I100041,C326923,Female,50,Cosmetics,3,121.98,Cash,24-07-2022,Mall of Istanbul

In [53]:
df.shape

(1000, 10)

In [25]:
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall'],
      dtype='object')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      1000 non-null   object
 1   customer_id     1000 non-null   object
 2   gender          1000 non-null   object
 3   age             1000 non-null   int64
 4   category        1000 non-null   object
 5   quantity        1000 non-null   int64
 6   price           1000 non-null   float64
 7   payment_method  1000 non-null   object
 8   invoice_date    1000 non-null   object
 9   shopping_mall   1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

In [27]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.dtypes

invoice_no         object
customer_id        object
gender             object
age                 int64
category           object
quantity            int64
price             float64
payment_method     object
invoice_date       object
shopping_mall      object
dtype: object

In [30]:
df.describe()

               age     quantity        price
count  1000.000000  1000.000000  1000.000000
mean     43.571000     2.981000   653.015770
std      15.283276     1.377874   907.245162
min      18.000000     1.000000     5.230000
25%      30.000000     2.000000    46.920000
50%      43.000000     3.000000   203.300000
75%      57.000000     4.000000   937.680000
max      69.000000     5.000000  5250.000000

In [54]:
df.select_dtypes(include="object").columns

Index(['invoice_no', 'customer_id', 'gender', 'category', 'payment_method',
       'invoice_date', 'shopping_mall'],
      dtype='object')

In [32]:
df.select_dtypes(include="object").nunique()

invoice_no        1000
customer_id       1000
gender               2
category             8
payment_method       3
invoice_date       580
shopping_mall       10
dtype: int64

In [33]:
df.select_dtypes(include="object").apply(lambda X:X.unique())

invoice_no        [I100008, I100014, I100015, I100024, I100027, ...
customer_id       [C199951, C138893, C132779, C244411, C150002, ...
gender                                               [Male, Female]
category          [Clothing, Cosmetics, Books, Technology, Food ...
payment_method                      [Cash, Debit Card, Credit Card]
invoice_date      [10-07-2022, 18-06-2021, 04-03-2021, 05-01-202...
shopping_mall     [Emaar Square Mall, Viaport Outlet, Mall of Is...
dtype: object

In [35]:
df["revenue"]=df["quantity"]*df["price"]

In [36]:
df[["quantity","price","revenue"]].head()

   quantity    price   revenue
0         5  1500.40   7502.00
1         5   203.30   1016.50
2         2   600.16   1200.32
3         3    45.45    136.35
4         4  4200.00  16800.00

In [37]:
df.groupby("gender").agg(products=("quantity","sum"),revenue=("revenue","sum"))

        products     revenue
gender
Female      1853  1408881.11
Male        1128   956486.66

In [38]:
df["age_cat"]=pd.cut(
    df["age"],
    bins=[0,18,30,45,60,100],
    labels=["0-18","19-30","31-45","46-60","61+"])

In [39]:
df[["age","age_cat"]].head()

   age age_cat
0   65     61+
1   55   46-60
2   35   31-45
3   67     61+
4   19   19-30

In [40]:
df.groupby("age_cat",observed=True)["quantity"].sum()

age_cat
0-18      74
19-30    707
31-45    869
46-60    799
61+      532
Name: quantity, dtype: int64

In [41]:
df.groupby("age_cat",observed=True)["revenue"].sum()

age_cat
0-18      35724.36
19-30    533548.82
31-45    663419.18
46-60    616237.97
61+      516437.44
Name: revenue, dtype: float64

In [42]:
df.groupby("payment_method")["invoice_no"].count()

payment_method
Cash           420
Credit Card    366
Debit Card     214
Name: invoice_no, dtype: int64

In [43]:
df.groupby("payment_method")["quantity"].sum()

payment_method
Cash           1271
Credit Card    1069
Debit Card      641
Name: quantity, dtype: int64

In [44]:
df.groupby("payment_method")["revenue"].sum()

payment_method
Cash           1041239.48
Credit Card     770272.60
Debit Card      553855.69
Name: revenue, dtype: float64

In [45]:
df.to_csv("customer_cleaned.csv",index=False)

In [55]:
import os
os.getcwd()

'C:\\Users\\ravur\\Downloads'